### ISSUE TITLE
Express 5 | TypeError: obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by itsTeknas** [mariusc23/express-query-boolean#11]
Started getting this error after upgrading to express 5
```
TypeError: obj.hasOwnProperty is not a function
    at parseObject (/Users/Sanket/Workspace/X/node_modules/express-query-boolean/lib/parse.js:60:13)
    at /Users/Sanket/Workspace/X/node_modules/express-query-boolean/index.js:5:17
```

Maybe it's linked to this
https://expressjs.com/en/guide/migrating-5.html#req.query

> req.query
The req.query property is no longer a writable property and is instead a getter. The default query parser has been changed from “extended” to “simple”.

**Comment by eliliam** [comment]
Has anyone found a fix for this?

**Comment by merwan** [comment]
> Has anyone found a fix for this?

Setting the application parameter for `query parser` setting to `extended` in your `app.js` should fix the issue: https://expressjs.com/en/5x/api/application/#application-settings
```js
app.set("query parser", "extended");
```
